### ISSUE TITLE
cpexcel.js problem

### ISSUE THREAD

**Issue by volodymyrl** [SheetJS/js-xlsx#76]
Hi! I try use js-xlsx, bower and glup, but when I added 2 files to my progect 

require('../vendors/js-xlsx/dist/jszip.js');
require('../vendors/js-xlsx/xlsx.js');

I got this error 

{ [Error: module "./cptable" not found from "F:\.......\vendors\js-xlsx\dist\cpexcel.js"]
  plugin: 'gulp-browserify',
  showStack: undefined,
  name: 'Error',
  message: 'module "./cptable" not found from "F:\\.......\\vendors\\js-xlsx\\dist\\cpexcel.js"',
  fileName: undefined,
  lineNumber: undefined

I have  cpexcel.js file in 'dist' folder.
Any idia how I can fix it? Thanks!

**Comment by SheetJSDev** [comment]
We pushed version 0.8.7 with modified require paths.  Please check whether this resolves the issue.

**Comment by jayabhar** [comment]
I am still getting the same error.

Cannot resolve file or directory ./cptable in ./node_modules/xlsx/dist

**Comment by SheetJSDev** [comment]
@jayabhar can you share a sample?  I just checked and the [demos](https://github.com/SheetJS/js-xlsx/tree/master/demos) seem to work

**Comment by jayabhar** [comment]
I had another issue with my local configuration. With the latest version 0.8.7 along with web-pack demo config changes, it works perfect. Thanks for the support.

**Comment by jayabhar** [comment]
Hello,
 Thanks for responding to my query very quickly. It was impressive.

I am right now trying to export a json data to an excel file using sheet.js
client side logic. But I am not able to create a workbook object to insert
the json data to it. I could not find a proper info on the documentation
too. could you help me with it ?

My code looks like this:



    const wopts = { bookType: 'xlsx', bookSST: false, type: 'binary' };
    const wbout = XLSX.write(wb, wopts); // How do I initialize 'wb' to use
it here ?

    function s2ab(s) {
      const buf = new ArrayBuffer(s.length);
      const view = new Uint8Array(buf);
      for (let i = 0; i !== s.length; ++i) view[i] = s.charCodeAt(i) & 0xFF;
      return buf;
    }

    saveAs(new Blob([s2ab(wbout)], { type: 'application/octet-stream' }),
'test.xlsx');




   - *Jayabhargava*



    <https://in.linkedin.com/in/jayabhargava>

**Comment by SheetJSDev** [comment]
@jayabhar Workbook object needs a `SheetNames` array of strings and a `Sheets` object whose keys are sheet names and whose values are worksheets.  see https://github.com/SheetJS/js-xlsx#workbook--worksheet--cell-object-description for a description.

As a simple example, here's a workbook with 2 worksheets:

```
var wb = {SheetNames:[], Sheets:{}};

/* first worksheet */
var sheet1 = {};

/* text */
sheet1.A1 = {t:'s', v:"one"};
sheet1.A2 = {t:'s', v:"two"};

/* numbers */
sheet1.B1 = {t:'n', v:1};
sheet1.B2 = {t:'n', v:2};

/* set sheet range */
sheet1['!ref'] = "A1:B2"; 

/* add to workbook */
wb.SheetNames.push("Sheet1"); wb.Sheets["Sheet1"] = sheet1;

/* second worksheet */
var sheet2 = {};
sheet2.A1 = {t:'n', v:3};
sheet2.B1 = {t:'s', v:"three"};
sheet2.A2 = {t:'s', v:"four"};
sheet2.B2 = {t:'n', v:4};
sheet2['!ref'] = "A1:B2"; 
wb.SheetNames.push("Sheet2"); wb.Sheets["Sheet2"] = sheet2;
```
